apiVersion: 0.1.0
environments:
  minikube:
    destination:
      namespace: default
      server: https://192.168.99.100:8443
    k8sVersion: v1.7.0
    path: minikube
kind: ksonnet.io/app
name: test-app
registries:
  incubator:
    gitVersion:
      commitSha: 422d521c05aa905df949868143b26445f5e4eda5
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
